
CREATE TABLE public.registos_horas (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       created_at timestamp(6) NOT NULL,
                                       data_registo date NOT NULL,
                                       descricao varchar(500) NULL,
                                       hora_entrada time(6) NOT NULL,
                                       hora_saida time(6) NULL,
                                       horas_trabalhadas float8 NULL,
                                       public_id uuid NOT NULL,
                                       updated_at timestamp(6) NULL,
                                       username varchar(100) NOT NULL,
                                       CONSTRAINT registos_horas_pkey PRIMARY KEY (id),
                                       CONSTRAINT ukcqw8np2h7rop964jyteuhbuiy UNIQUE (public_id)
);